[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; Librerie esterne necessarie (Useremo una leggera per l'IMU per fare prima, poi la customizzeremo se serve)
lib_deps = 
    rfetick/MPU6050_light @ ^1.1.0

; Flags di compilazione per debug e inclusione header globali
build_flags = 
    -D CORE_DEBUG_LEVEL=0
    -I include
